WITH CTE AS(

select 
TO_TIMESTAMP(STARTTIME) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTTIME)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTTIME)) AS HOUR_STARTED_AT,

CASE 
WHEN DAYNAME(TO_TIMESTAMP(STARTTIME)) in ('Sat','Sun')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,
CASE WHEN MONTH(TO_TIMESTAMP(STARTTIME)) in (12,1,2)
    THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTTIME)) in (3,4,5)
    THEN 'SPRING'
    WHEN MONTH(TO_TIMESTAMP(STARTTIME)) in (6,7,8)
    THEN 'SUMMER'
    ELSE 'AUTUMN' 
    END AS STATION_OF_YEAR

from
{{ source('demo', 'bike') }}


)

select * from CTE