WITH CTE AS(

select 
TO_TIMESTAMP(STARTTIME) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTTIME)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTTIME)) AS HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTTIME)) AS DAY_NAME

from
{{ source('demo', 'bike') }}


)

select * from CTE