WITH TRIPS as (

select 
BIKEID,
USERTYPE,
BIRTH_YEAR,
TO_TIMESTAMP(STARTTIME) AS STARTTIMES,
DATE(TO_TIMESTAMP(STARTTIME)) AS STARTDATE,
TO_TIMESTAMP(STOPTIME) AS STOPTIMES,
TIMESTAMPDIFF(SECONDS,TO_TIMESTAMP(STARTTIME),TO_TIMESTAMP(STOPTIME)) AS TRIP_DURATION_SECONDS

from {{ source('demo', 'bike') }}

)

select * from TRIPS